### PR TITLE
Add travis support, build as non-root 

### PR DESCRIPTION
**Pull request by jprjr**
This does a couple of things for issue #5 
- The Docker image builds everything as not-root
- This add a travis.yml file to auto-compile and upload to GitHub releases

The reason for non-root - Travis has a significantly faster build system that uses containers instead of VMs, but you can't use 'sudo' within that environment.

@glerchundi , Instead of just merging like usual, I'll let you review+merge this.

I'm not sure if Travis will work correctly, I might have to redo that api_key bit in .travis.yml. We'll just have to see!

### CODE REVIEW

**Comment by glerchundi** [comment]
Wow, this rules!

How do you set the release description?

**Comment by jprjr** [comment]
I'll be honest, I have no idea 

On March 12, 2015 12:16:38 PM CDT, Gorka Lerchundi Osa notifications@github.com wrote:

> Wow, this rules!
> 
> How do you set the release description?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/just-containers/skaware-builder/pull/6#issuecomment-78533885

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by glerchundi** [comment]
hahaha! ok, we'll investigate, it would be cool to put releases.md content in the description :). Anyway, great work! give me until tomorrow to see how everything works, ok?

**Comment by jprjr** [comment]
Sounds good!

**Comment by glerchundi** [comment]
I've copied your implementation to do more or less the same for s6-overlay-builder but it doesn't work due to bad credentials...and i don't know how to tackle this...

anyway, can you rebase/squash into one commit and we'll merge although it's not gonna work (i think) right now.

**Comment by glerchundi** [comment]
i know why my pull didn't worked, I `travis encrypt` locally inside my fork which is `glerchundi/s6-overlay-builder` and wanted to encrypt my personal access token. But, destination repository must be referenced directly: `travis encrypt -r just-container/s6-overlay-builder gh_token`. I don't know if you already do that but just in case ;)

**Comment by jprjr** [comment]
Let's see what happens! if I have to change the token, I'll get it done shortly.

**Comment by glerchundi** [comment]
i changed access token and now it works, good job!

**Pull request merged**
